services:
  - name: vendora-backend
    type: web
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "8000"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false

  - name: vendora-frontend
    type: web
    runtime: static
    rootDir: frontend
    staticPublishPath: build/web
    envVars:
      - key: API_BASE_URL
        value: https://vendora-backend.onrender.com/api
      - key: GEMINI_API_KEY
        sync: false
